### ISSUE TITLE
Don't use custom attributes

### ISSUE THREAD

**Issue by odysseuscm** [pytesNET/tail.tooltip#1]
Nice plug-in, but you shouldn't use custom attributes like "tail-tooltip" - they don't validate. That's what data- attributes are for. So if you change your custom attributes to "data-tail-tooltip" etc. the html will be valid.

**Comment by SamBrishes** [comment]
Hello,

Thank you! :D 
I've changed it into `data-tooltip`, `data-tooltip-conf` and `data-tooltip-style`.

Sincerely,
Sam.
